import { INerd } from './types'

export const traits = [
  'strength',
  'dexterity',
  'wisdom',
  'intelligence',
  'charisma',
  'constitution'
]

export const players: INerd[] = [
  {
    id: 'potter',
    name: 'Harry Potter',
    level: 10,
    boost: 1,
    traits: {
      strength: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      dexterity: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      wisdom: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      intelligence: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      charisma: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      constitution: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
    }
  },
  {
    id: 'hermione',
    name: 'Hermione Granger',
    level: 10,
    boost: 1,
    traits: {
      strength: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      dexterity: {
        rating: 1400,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      wisdom: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      intelligence: {
        rating: 1600,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      charisma: {
        rating: 1300,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      constitution: {
        rating: 1200,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
    }
  },
  {
    id: 'ron',
    name: 'Ron Weasley',
    level: 10,
    boost: 1,
    traits: {
      strength: {
        rating: 1600,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      dexterity: {
        rating: 1600,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      wisdom: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      intelligence: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      charisma: {
        rating: 1400,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      constitution: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
    }
  },
  {
    id: 'draco',
    name: 'Draco Malfoy',
    level: 5,
    boost: 1,
    traits: {
      strength: {
        rating: 1400,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      dexterity: {
        rating: 1600,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      wisdom: {
        rating: 800,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      intelligence: {
        rating: 900,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      charisma: {
        rating: 1700,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      constitution: {
        rating: 1500,
        ratingShift: 0,
        rd: 300,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
    }
  },
  {
    id: 'dumbledore',
    name: 'Albus Dumbledore',
    level: 100,
    boost: 1,
    traits: {
      strength: {
        rating: 2000,
        ratingShift: 0,
        rd: 100,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      dexterity: {
        rating: 1400,
        ratingShift: 0,
        rd: 100,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      wisdom: {
        rating: 2200,
        ratingShift: 0,
        rd: 100,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      intelligence: {
        rating: 2100,
        ratingShift: 0,
        rd: 100,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      charisma: {
        rating: 1900,
        ratingShift: 0,
        rd: 100,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
      constitution: {
        rating: 1000,
        ratingShift: 0,
        rd: 100,
        volatility: 0.06,
        glicko: null,
        boost: 1,
      },
    }
  },
]